name: CI Workflow
on: [push]
jobs:
  build-and-test:
    name: Build and run tests
    # runs-on: ubuntu-latest
    runs-on: macos-latest # Switched to macOS
    steps:
          - name: Run unit tests
            run: ./gradlew testDebugUnitTest
          - name: Run instrumentation tests
            uses: reactivecircus/android-emulator-runner@v2
            with:
              api-level: 29
              arch: x86
              profile: Nexus 6
              avd-name: test
              emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
              disable-animations: true
              script: ./gradlew connectedCheck
